/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/utils/export.js
var export_exports = {};
__export(export_exports, {
  exportHighlightsToMD: () => exportHighlightsToMD,
  getHighlightsFromContent: () => getHighlightsFromContent
});
async function exportHighlightsToMD(app, file) {
  const raw = await app.vault.read(file);
  const highlights = [];
  const markdownPattern = /==(.*?)==/gs;
  const htmlPattern = /<mark[^>]*>(.*?)<\/mark>/gs;
  let match;
  while ((match = markdownPattern.exec(raw)) !== null) {
    highlights.push({
      text: match[1].trim(),
      type: "markdown",
      position: match.index
    });
  }
  while ((match = htmlPattern.exec(raw)) !== null) {
    highlights.push({
      text: match[1].trim(),
      type: "html",
      position: match.index
    });
  }
  highlights.sort((a, b) => a.position - b.position);
  if (highlights.length === 0) {
    throw new Error("No highlights found in this file.");
  }
  const date = window.moment ? window.moment().format("YYYY-MM-DD HH:mm") : (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const exportContent = `# Highlights from [[${file.basename}]]

> Exported: ${date}
> Source: [[${file.path}]]
> Total highlights: ${highlights.length}

---

${highlights.map((h, i) => `${i + 1}. ${h.text}`).join("\n\n")}

---

*Exported by Reader Highlighter Tags*
`;
  let exportPath = `${file.parent.path}/${file.basename} - Highlights.md`;
  const existingFile = app.vault.getAbstractFileByPath(exportPath);
  if (existingFile) {
    const timestamp = window.moment ? window.moment().format("YYYYMMDD-HHmmss") : Date.now();
    exportPath = `${file.parent.path}/${file.basename} - Highlights ${timestamp}.md`;
  }
  await app.vault.create(exportPath, exportContent);
  return exportPath;
}
function getHighlightsFromContent(raw) {
  const highlights = [];
  const lines = raw.split("\n");
  const markdownPattern = /==(.*?)==/g;
  const htmlPattern = /<mark[^>]*>(.*?)<\/mark>/g;
  lines.forEach((line, lineIdx) => {
    let match;
    while ((match = markdownPattern.exec(line)) !== null) {
      highlights.push({
        text: match[1].trim(),
        line: lineIdx,
        type: "markdown"
      });
    }
    while ((match = htmlPattern.exec(line)) !== null) {
      const colorMatch = match[0].match(/background:\s*([^;>"]+)/);
      highlights.push({
        text: match[1].trim(),
        line: lineIdx,
        type: "html",
        color: colorMatch ? colorMatch[1].trim() : null
      });
    }
  });
  return highlights;
}
var init_export = __esm({
  "src/utils/export.js"() {
  }
});

// src/main.js
var main_exports = {};
__export(main_exports, {
  default: () => ReadingHighlighterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/ui/FloatingManager.js
var import_obsidian = require("obsidian");
var FloatingManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.app = plugin.app;
    this.containerEl = null;
    this.highlightBtn = null;
    this.tagBtn = null;
    this.removeBtn = null;
    this.quoteBtn = null;
    this.annotateBtn = null;
    this.colorButtons = [];
    this.paletteContainer = null;
    this._handlers = [];
    this.longPressTimer = null;
    this._selectionDebounceTimer = null;
    this._selectionSnapshot = null;
  }
  load() {
    this.createElements();
    this.registerEvents();
    if (import_obsidian.Platform.isMobile) {
      this.setupMobileGestures();
    }
  }
  unload() {
    var _a;
    (_a = this.containerEl) == null ? void 0 : _a.remove();
    this.containerEl = null;
    this._handlers.forEach((cleanup) => cleanup());
    this._handlers = [];
    if (this._selectionDebounceTimer) {
      clearTimeout(this._selectionDebounceTimer);
      this._selectionDebounceTimer = null;
    }
  }
  refresh() {
    if (this.containerEl) {
      this.containerEl.remove();
      this.containerEl = null;
    }
    this.colorButtons = [];
    this.createElements();
    this.registerEvents();
  }
  createElements() {
    if (this.containerEl)
      return;
    this.containerEl = document.createElement("div");
    this.containerEl.addClass("reading-highlighter-float-container");
    this.highlightBtn = this.createButton("highlighter", "Highlight selection");
    this.containerEl.appendChild(this.highlightBtn);
    if (this.plugin.settings.enableColorPalette) {
      this.paletteContainer = document.createElement("div");
      this.paletteContainer.addClass("reading-highlighter-palette");
      this.plugin.settings.colorPalette.forEach((item, index) => {
        const colorBtn = document.createElement("button");
        colorBtn.addClass("reading-highlighter-color-btn");
        colorBtn.style.backgroundColor = item.color;
        colorBtn.setAttribute("aria-label", item.name);
        colorBtn.setAttribute("data-color-index", index.toString());
        this.colorButtons.push(colorBtn);
        this.paletteContainer.appendChild(colorBtn);
      });
      this.containerEl.appendChild(this.paletteContainer);
    }
    if (this.plugin.settings.showTagButton) {
      this.tagBtn = this.createButton("tag", "Tag selection");
      this.containerEl.appendChild(this.tagBtn);
    }
    if (this.plugin.settings.showQuoteButton) {
      this.quoteBtn = this.createButton("quote", "Copy as quote");
      this.containerEl.appendChild(this.quoteBtn);
    }
    if (this.plugin.settings.enableAnnotations && this.plugin.settings.showAnnotationButton) {
      this.annotateBtn = this.createButton("message-square", "Add annotation");
      this.containerEl.appendChild(this.annotateBtn);
    }
    if (this.plugin.settings.showRemoveButton) {
      this.removeBtn = this.createButton("eraser", "Remove highlight");
      this.removeBtn.addClass("reading-highlighter-remove-btn");
      this.containerEl.appendChild(this.removeBtn);
    }
    document.body.appendChild(this.containerEl);
  }
  createButton(iconName, label) {
    const btn = document.createElement("button");
    (0, import_obsidian.setIcon)(btn, iconName);
    if (this.plugin.settings.showTooltips) {
      btn.setAttribute("aria-label", label);
    }
    btn.addClass("reading-highlighter-btn");
    return btn;
  }
  registerEvents() {
    const preventFocus = (evt) => {
      evt.preventDefault();
      evt.stopPropagation();
    };
    const attachAction = (btn, actionName) => {
      if (!btn)
        return;
      const handler = (evt) => {
        preventFocus(evt);
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (view && view.getMode() === "preview") {
          this.plugin[actionName](view, this._selectionSnapshot);
        }
        this.hide();
      };
      btn.addEventListener("mousedown", handler);
      btn.addEventListener("touchstart", handler, { passive: false });
    };
    attachAction(this.highlightBtn, "highlightSelection");
    attachAction(this.tagBtn, "tagSelection");
    attachAction(this.quoteBtn, "copyAsQuote");
    attachAction(this.annotateBtn, "annotateSelection");
    attachAction(this.removeBtn, "removeHighlightSelection");
    this.colorButtons.forEach((btn, index) => {
      const handler = (evt) => {
        preventFocus(evt);
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (view && view.getMode() === "preview") {
          this.plugin.applyColorByIndex(view, index, this._selectionSnapshot);
        }
        this.hide();
      };
      btn.addEventListener("mousedown", handler);
      btn.addEventListener("touchstart", handler, { passive: false });
    });
  }
  setupMobileGestures() {
    if (!import_obsidian.Platform.isIosApp)
      return;
    document.addEventListener("touchstart", (e) => {
      this.longPressTimer = setTimeout(() => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        const sel = window.getSelection();
        if (view && view.getMode() === "preview" && (sel == null ? void 0 : sel.toString().trim())) {
          this.plugin.highlightSelection(view);
          this.hide();
        }
      }, 600);
    }, { passive: true });
    document.addEventListener("touchmove", () => {
      if (this.longPressTimer) {
        clearTimeout(this.longPressTimer);
        this.longPressTimer = null;
      }
    }, { passive: true });
    document.addEventListener("touchend", () => {
      if (this.longPressTimer) {
        clearTimeout(this.longPressTimer);
        this.longPressTimer = null;
      }
    }, { passive: true });
  }
  /**
   * Called on every `selectionchange` event.
   * On Android the event fires per-word during a drag, so we debounce it
   * to wait for the selection to settle before showing the toolbar.
   * On iOS/Desktop we keep the original instant behaviour.
   */
  handleSelection() {
    if (import_obsidian.Platform.isAndroidApp) {
      if (this._selectionDebounceTimer) {
        clearTimeout(this._selectionDebounceTimer);
      }
      this._selectionDebounceTimer = setTimeout(() => {
        this._selectionDebounceTimer = null;
        this._doHandleSelection();
      }, 300);
    } else {
      this._doHandleSelection();
    }
  }
  /** Internal: actually process the current selection state. */
  _doHandleSelection() {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view || view.getMode() !== "preview") {
      this.hide();
      return;
    }
    const sel = window.getSelection();
    const snippet = (_a = sel == null ? void 0 : sel.toString()) != null ? _a : "";
    if (snippet.trim() && sel && !sel.isCollapsed && sel.rangeCount > 0) {
      const range = sel.getRangeAt(0);
      const rect = range.getBoundingClientRect();
      this._selectionSnapshot = {
        text: snippet,
        range: range.cloneRange()
      };
      this.show(rect);
    } else {
      this._selectionSnapshot = null;
      this.hide();
    }
  }
  show(rect) {
    if (!this.containerEl || !rect)
      return;
    this.containerEl.style.display = "flex";
    this.containerEl.style.top = "";
    this.containerEl.style.bottom = "";
    this.containerEl.style.left = "";
    this.containerEl.style.right = "";
    this.containerEl.style.transform = "";
    this.containerEl.removeClass("reading-highlighter-vertical");
    const pos = this.plugin.settings.toolbarPosition || "text";
    if (pos === "text") {
      const containerHeight = 50;
      const containerWidth = this.plugin.settings.enableColorPalette ? 280 : 180;
      if (import_obsidian.Platform.isAndroidApp) {
        const gap = 12;
        let top = rect.bottom + gap;
        let left = rect.left + rect.width / 2 - containerWidth / 2;
        if (top + containerHeight > window.innerHeight - 10) {
          top = rect.top - containerHeight - 60;
        }
        if (top < 10)
          top = 10;
        if (left < 10)
          left = 10;
        if (left + containerWidth > window.innerWidth - 10) {
          left = window.innerWidth - containerWidth - 10;
        }
        this.containerEl.style.top = `${top}px`;
        this.containerEl.style.left = `${left}px`;
      } else {
        let top = rect.top - containerHeight - 10;
        let left = rect.left + rect.width / 2 - containerWidth / 2;
        if (top < 10)
          top = rect.bottom + 10;
        if (left < 10)
          left = 10;
        if (left + containerWidth > window.innerWidth - 10) {
          left = window.innerWidth - containerWidth - 10;
        }
        this.containerEl.style.top = `${top}px`;
        this.containerEl.style.left = `${left}px`;
      }
    } else if (pos === "top") {
      this.containerEl.style.top = "80px";
      this.containerEl.style.left = "50%";
      this.containerEl.style.transform = "translateX(-50%)";
    } else if (pos === "bottom") {
      this.containerEl.style.bottom = "100px";
      this.containerEl.style.left = "50%";
      this.containerEl.style.transform = "translateX(-50%)";
    } else if (pos === "left") {
      this.containerEl.style.top = "50%";
      this.containerEl.style.left = "10px";
      this.containerEl.style.transform = "translateY(-50%)";
      this.containerEl.addClass("reading-highlighter-vertical");
    } else if (pos === "right") {
      this.containerEl.style.top = "50%";
      this.containerEl.style.right = "10px";
      this.containerEl.style.transform = "translateY(-50%)";
      this.containerEl.addClass("reading-highlighter-vertical");
    }
  }
  hide() {
    if (this.containerEl) {
      this.containerEl.style.display = "none";
    }
  }
};

// src/core/SelectionLogic.js
var BLOCK_LEVEL_TAGS_FOR_SPLIT = /* @__PURE__ */ new Set([
  "P",
  "LI",
  "BLOCKQUOTE",
  "PRE",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "TD",
  "TH"
]);
var GAP_PATTERN = "[\\s\\u00a0\\u1680\\u2000-\\u200b\\u202f\\u205f\\u3000\\u21a9\\u21b5\\ufe0e\\ufe0f]";
var INLINE_DECORATION_PATTERN = "(?:<mark[^>]*>|<\\/mark>|==|\\*\\*|~~|\\*|_|`)";
var OPTIONAL_MARKDOWN_LINE_PREFIX = "[ \\t]{0,3}(?:(?:>\\s*)*(?:#{1,6}[ \\t]+|-\\s\\[[ xX]\\][ \\t]+|[-*+][ \\t]+|\\d{1,3}[.)][ \\t]+|\\[\\^[^\\]]+\\]:[ \\t]*))?";
var MARKDOWN_PREFIX_ONLY_RE = /^[ \t]*(?:(?:>\s*)+|#{1,6}[ \t]*|-\s\[[ xX]\][ \t]*|[-*+][ \t]*|\d{1,3}[.)][ \t]*|\[\^[^\]]+\]:[ \t]*)+$/;
var INLINE_DECORATION_RE = /<mark[^>]*>|<\/mark>|==|\*\*|~~|\*|_|`/g;
var SelectionLogic = class {
  constructor(app) {
    this.app = app;
    this.blockLevelTagsForSplit = BLOCK_LEVEL_TAGS_FOR_SPLIT;
  }
  async locateSelection(processedFile, view, selectionSnippet, context = null, occurrenceIndex = 0) {
    const snippet = this.stripBrowserJunk(selectionSnippet);
    if (!snippet) {
      return null;
    }
    const activeFile = view.file;
    const opContext = { cache: /* @__PURE__ */ new Map(), visited: /* @__PURE__ */ new Set() };
    const virtual = await this.resolveVirtualContent(activeFile, 0, opContext);
    const fullRaw = virtual.text;
    let firstSegmentBodyStart = 0;
    if (fullRaw.startsWith("---")) {
      const secondDash = fullRaw.indexOf("---", 3);
      if (secondDash !== -1) {
        firstSegmentBodyStart = secondDash + 3;
        while (firstSegmentBodyStart < fullRaw.length && (fullRaw[firstSegmentBodyStart] === "\n" || fullRaw[firstSegmentBodyStart] === "\r")) {
          firstSegmentBodyStart++;
        }
      }
    }
    const bodyContent = fullRaw.substring(firstSegmentBodyStart);
    const selectionBlocks = this.splitSelectionBlocks(snippet);
    let candidates = selectionBlocks.length > 1 ? this.findBlockSequenceCandidates(bodyContent, selectionBlocks, 0) : [];
    if (candidates.length === 0) {
      candidates = this.findAllCandidates(bodyContent, snippet, 0);
    }
    if (candidates.length === 0) {
      candidates = this.findCandidatesStripped(bodyContent, snippet, 0);
    }
    if (candidates.length === 0) {
      candidates = this.findFuzzyCandidates(bodyContent, snippet, 0);
    }
    if (candidates.length === 0) {
      return null;
    }
    candidates = this.offsetCandidates(candidates, firstSegmentBodyStart);
    const result = this.resolveCandidates(candidates, fullRaw, context, occurrenceIndex);
    if (!result) {
      return null;
    }
    return this.mapVirtualToPhysical(result.start, result.end, virtual.segments);
  }
  async resolveVirtualContent(file, depth = 0, opContext = { cache: /* @__PURE__ */ new Map(), visited: /* @__PURE__ */ new Set() }) {
    if (depth > 5) {
      return { text: "", segments: [] };
    }
    if (opContext.cache.has(file.path)) {
      return opContext.cache.get(file.path);
    }
    if (opContext.visited.has(file.path)) {
      return { text: "", segments: [] };
    }
    opContext.visited.add(file.path);
    let raw = await this.app.vault.read(file);
    let fmOffset = 0;
    if (depth > 0 && raw.startsWith("---")) {
      const originalLength = raw.length;
      const secondDash = raw.indexOf("---", 3);
      if (secondDash !== -1) {
        raw = raw.substring(secondDash + 3);
        while (raw.startsWith("\n") || raw.startsWith("\r")) {
          raw = raw.substring(1);
        }
        fmOffset = originalLength - raw.length;
      }
    }
    const cache = this.app.metadataCache.getFileCache(file);
    const embeds = (cache == null ? void 0 : cache.embeds) || [];
    const sortedEmbeds = [...embeds].sort((a, b) => a.position.start.offset - b.position.start.offset);
    let virtualText = "";
    const segments = [];
    let lastOffset = 0;
    for (const embed of sortedEmbeds) {
      const adjustedStart = embed.position.start.offset - fmOffset;
      const adjustedEnd = embed.position.end.offset - fmOffset;
      if (adjustedStart < 0)
        continue;
      const preText = raw.substring(lastOffset, adjustedStart);
      const segStart = virtualText.length;
      virtualText += preText;
      segments.push({
        vStart: segStart,
        vEnd: virtualText.length,
        file,
        pOffset: lastOffset + fmOffset
      });
      const targetFile = this.app.metadataCache.getFirstLinkpathDest(embed.link.split("#")[0], file.path);
      if (targetFile) {
        const subContext = { ...opContext, visited: new Set(opContext.visited) };
        const subVirtual = await this.resolveVirtualContent(targetFile, depth + 1, subContext);
        const embedStart = virtualText.length;
        virtualText += subVirtual.text;
        for (const subSeg of subVirtual.segments) {
          segments.push({
            vStart: subSeg.vStart + embedStart,
            vEnd: subSeg.vEnd + embedStart,
            file: subSeg.file,
            pOffset: subSeg.pOffset
          });
        }
      } else {
        const embedText = raw.substring(adjustedStart, adjustedEnd);
        const segStart2 = virtualText.length;
        virtualText += embedText;
        segments.push({
          vStart: segStart2,
          vEnd: virtualText.length,
          file,
          pOffset: adjustedStart + fmOffset
        });
      }
      lastOffset = adjustedEnd;
    }
    const tailText = raw.substring(lastOffset);
    const tailStart = virtualText.length;
    virtualText += tailText;
    segments.push({
      vStart: tailStart,
      vEnd: virtualText.length,
      file,
      pOffset: lastOffset + fmOffset
    });
    const result = { text: virtualText, segments };
    opContext.cache.set(file.path, result);
    return result;
  }
  mapVirtualToPhysical(vStart, vEnd, segments) {
    const startSeg = segments.find((s) => vStart >= s.vStart && vStart < s.vEnd);
    const endSeg = segments.find((s) => vEnd > s.vStart && vEnd <= s.vEnd);
    if (!startSeg || !endSeg)
      return null;
    const pStart = startSeg.pOffset + (vStart - startSeg.vStart);
    const pEnd = endSeg.pOffset + (vEnd - endSeg.vStart);
    return {
      file: startSeg.file,
      start: pStart,
      end: pEnd,
      raw: ""
    };
  }
  resolveCandidates(candidates, raw, context, occurrenceIndex) {
    if (candidates.length === 0)
      return null;
    if (context) {
      const cleanContext = context.replace(/\s+/g, " ").trim();
      candidates = candidates.map((cand) => {
        const sourceBlock = (cand.text || raw.substring(cand.start, cand.end)).replace(/\s+/g, " ").trim();
        const score = this.calculateSimilarity(sourceBlock, cleanContext);
        return { ...cand, score };
      });
      const bestScore = Math.max(...candidates.map((candidate) => candidate.score));
      const threshold = bestScore * 0.85;
      const validCandidates = candidates.filter((candidate) => candidate.score >= threshold);
      if (occurrenceIndex >= 0 && occurrenceIndex < validCandidates.length) {
        const chosen = validCandidates[occurrenceIndex];
        return { raw, start: chosen.start, end: chosen.end };
      }
      if (validCandidates.length > 0) {
        return { raw, start: validCandidates[0].start, end: validCandidates[0].end };
      }
    }
    return { raw, start: candidates[0].start, end: candidates[0].end };
  }
  createFlexiblePattern(snippet) {
    const lines = this.splitSelectionBlocks(this.stripUrlsForPatternMatch(snippet), false);
    if (lines.length === 0) {
      return "";
    }
    const contentPatterns = lines.map((line) => this.createFlexibleLinePattern(line));
    const lineBridge = `(?:[ \\t]*(?:${INLINE_DECORATION_PATTERN}){0,3}[ \\t]*\\r?\\n(?:[ \\t>]*\\r?\\n){0,3})`;
    const joined = contentPatterns.map((pattern, index) => {
      const linePattern = `${OPTIONAL_MARKDOWN_LINE_PREFIX}${pattern}`;
      return index === 0 ? linePattern : `${lineBridge}${linePattern}`;
    }).join("");
    return joined;
  }
  createFlexibleLinePattern(line) {
    const normalizedLine = this.normalizeComparableText(line);
    const parts = [];
    let pendingGap = false;
    for (let i = 0; i < normalizedLine.length; i++) {
      const char = normalizedLine[i];
      if (/\s/.test(char)) {
        pendingGap = true;
        continue;
      }
      if (pendingGap && parts.length > 0) {
        parts.push(`(?:${GAP_PATTERN}|[-\u2010-\u2015]|"|'|[\u201C\u201D\u2018\u2019\xAB\xBB]){1,3}`);
        pendingGap = false;
      }
      parts.push(this.getFlexibleCharPattern(char));
      if (i < normalizedLine.length - 1) {
        parts.push(`(?:${GAP_PATTERN}|[-\u2010-\u2015]|"|'|[\u201C\u201D\u2018\u2019\xAB\xBB]|[\\*_~=]){0,3}`);
      }
    }
    if (parts.length === 0) {
      return "";
    }
    return parts.join("");
  }
  getFlexibleCharPattern(char) {
    if (char === "-") {
      return "[-\u2010-\u2015]";
    }
    if (char === '"') {
      return '["\u201C\u201D\xAB\xBB]';
    }
    if (char === "'") {
      return "['\u2018\u2019`]";
    }
    return this.escapeRegex(char);
  }
  stripBrowserJunk(text) {
    if (!text) {
      return text;
    }
    // AMENDED: Removed the footnote-stripping regex to fix Ensor paragraph highlights
    return text.normalize("NFC").replace(/#:~:text=[^&\s]+(?:&|$)?/g, "").replace(/[\u200b-\u200d\ufeff]/g, "").replace(/(?:\u21a9|\u21b5|\ufe0e|\ufe0f)+/g, " ").replace(/[\u00a0\u202f]/g, " ").replace(/[‐‑‒–—―]/g, "-").replace(/[“”«»]/g, '"').replace(/[‘’]/g, "'").replace(/\s+/g, " ").trim();
  }
  stripUrlsForPatternMatch(snippet) {
    return snippet.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/<https?:\/\/[^>]+>/g, "");
  }
  findAllCandidates(text, snippet, bodyStart = 0) {
    const cleanSnippet = snippet.trim();
    if (!cleanSnippet) {
      return [];
    }
    const patternSnippet = this.stripUrlsForPatternMatch(cleanSnippet);
    if (!patternSnippet) {
      return [];
    }
    if (patternSnippet.length > 800) {
      const startAnchor = patternSnippet.substring(0, 150);
      const endAnchor = patternSnippet.substring(patternSnippet.length - 150);
      const startP = this.createFlexiblePattern(startAnchor);
      const endP = this.createFlexiblePattern(endAnchor);
      let startRegex;
      let endRegex;
      try {
        startRegex = new RegExp(startP, "gmu");
        endRegex = new RegExp(endP, "gmu");
      } catch (e) {
        console.error("INVALID REGEX PATTERN (anchor):", e);
        return [];
      }
      const startMatches = [];
      const endMatches = [];
      let match2;
      try {
        while ((match2 = startRegex.exec(text)) !== null) {
          if (match2.index >= bodyStart) {
            startMatches.push(match2);
          }
        }
      } catch (e) {
        console.warn("Regex execution failed on startRegex (mobile backtracking limit):", e);
        return [];
      }
      try {
        while ((match2 = endRegex.exec(text)) !== null) {
          if (match2.index >= bodyStart) {
            endMatches.push(match2);
          }
        }
      } catch (e) {
        console.warn("Regex execution failed on endRegex (mobile backtracking limit):", e);
        return [];
      }
      if (startMatches.length > 0 && endMatches.length > 0) {
        for (const startMatch of startMatches) {
          const bestEnd = endMatches.find((endMatch) => endMatch.index > startMatch.index && endMatch.index - startMatch.index < cleanSnippet.length * 2);
          if (bestEnd) {
            return [{
              start: startMatch.index,
              end: bestEnd.index + bestEnd[0].length,
              text: text.substring(startMatch.index, bestEnd.index + bestEnd[0].length)
            }];
          }
        }
      }
    }
    const pattern = this.createFlexiblePattern(patternSnippet);
    if (!pattern) {
      return [];
    }
    let regex;
    try {
      regex = new RegExp(pattern, "gmu");
    } catch (_error) {
      console.error("INVALID REGEX PATTERN:", pattern);
      return [];
    }
    const candidates = [];
    let match;
    try {
      while ((match = regex.exec(text)) !== null) {
        candidates.push({
          start: match.index,
          end: match.index + match[0].length,
          text: match[0]
        });
      }
    } catch (e) {
      console.warn("Regex execution failed in findAllCandidates (mobile backtracking limit):", e);
      return [];
    }
    return candidates;
  }
  escapeRegex(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  findCandidatesStripped(text, snippet, bodyStart = 0) {
    const map = [];
    let strippedRaw = "";
    const isFormattingMarker = (str, pos) => {
      const char = str[pos];
      const next1 = str[pos + 1];
      const next2 = str[pos + 2];
      if (char === "*" && next1 === "*" && next2 === "*") {
        return 3;
      }
      if (char === "*" && next1 === "*" || char === "~" && next1 === "~" || char === "=" && next1 === "=") {
        return 2;
      }
      if (char === "*" || char === "_") {
        return 1;
      }
      return 0;
    };
    const extractVisibleText = (startPos, endPos) => {
      for (let i = startPos; i < endPos; i++) {
        const skip = isFormattingMarker(text, i);
        if (skip > 0) {
          i += skip - 1;
          continue;
        }
        map.push(i);
        strippedRaw += text[i];
      }
    };
    const addRawText = (startPos, endPos) => {
      for (let i = startPos; i < endPos; i++) {
        map.push(i);
        strippedRaw += text[i];
      }
    };
    const tokenRegex = new RegExp([
      /(`{3}[^\n]*\n[\s\S]*?`{3})/.source,
      /(!\[\[(?:[^\]]+)\]\])/.source,
      /(!\[(?:[^\]]*)\]\[(?:[^\]]*)\])/.source,
      /(!\[(?:[^\]]*)\]\((?:[^()"]*(?:\([^)]*\))?[^()"]*(?:"[^"]*")?)\))/.source,
      /(\[(?!\^)(?:[^\]]+)\]\[(?:[^\]]*)\])/.source,
      /(\[(?!\^)(?:[^\]]+)\]\((?:[^()"]*(?:\([^)]*\))?[^()"]*(?:"[^"]*")?)\))/.source,
      /(\[\[(?:[^\]]+)\]\])/.source,
      /(\[\^[^\]]+\]:?[ \t]?)/.source,
      /(\$\$[^$]+\$\$)/.source,
      /(\$(?:[^$\s]|[^$\s][^$]*[^$\s])\$)/.source,
      /(%%[^%]*%%)/.source,
      /(`[^`]+`)/.source,
      /(<(?:https?:\/\/[^>]+|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})>)/.source,
      /(<\/?[a-zA-Z][^>]*>)/.source,
      /(\\(?:[*_[\](){}#>+\-.!`~=|\\]))/.source,
      /(\*\*\*)/.source,
      /(\*\*|~~|==)/.source,
      /(\*|_)/.source,
      /(^[ \t]*>[ \t]?(?:\[![^\]]+\][ \t]?)?)/.source,
      /([ \t]\^[a-zA-Z0-9-]+(?=\s|$))/.source,
      /(\|[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)*\|)/.source,
      /(\|)/.source,
      /([\u2013\u2014\u201c\u201d\u2018\u2019\u00ab\u00bb])/.source
    ].join("|"), "gm");
    let lastIndex = 0;
    let match;
    try {
      while ((match = tokenRegex.exec(text)) !== null) {
        for (let i = lastIndex; i < match.index; i++) {
          map.push(i);
          strippedRaw += text[i];
        }
        const fullMatch = match[0];
        const matchStart = match.index;
        if (match[1]) {
          const firstNewline = fullMatch.indexOf("\n");
          if (firstNewline !== -1) {
            const codeStart = matchStart + firstNewline + 1;
            const closingFence = fullMatch.lastIndexOf("```");
            const codeEnd = closingFence !== -1 ? matchStart + closingFence : matchStart + fullMatch.length;
            addRawText(codeStart, codeEnd);
          }
        } else if (match[2]) {
          const inner = fullMatch.substring(3, fullMatch.length - 2);
          const pipeIndex = inner.indexOf("|");
          const visibleStart = matchStart + 3 + (pipeIndex !== -1 ? pipeIndex + 1 : 0);
          const visibleEnd = matchStart + fullMatch.length - 2;
          extractVisibleText(visibleStart, visibleEnd);
        } else if (match[3] || match[4] || match[5] || match[6]) {
          const closingBracket = fullMatch.indexOf(match[3] || match[5] ? "][" : "](");
          const textStart = matchStart + (match[3] || match[4] ? 2 : 1);
          const textEnd = matchStart + (closingBracket !== -1 ? closingBracket : fullMatch.indexOf("]"));
          extractVisibleText(textStart, textEnd);
        } else if (match[7]) {
          const inner = fullMatch.substring(2, fullMatch.length - 2);
          const pipeIndex = inner.indexOf("|");
          const visibleStart = matchStart + 2 + (pipeIndex !== -1 ? pipeIndex + 1 : 0);
          const visibleEnd = matchStart + fullMatch.length - 2;
          extractVisibleText(visibleStart, visibleEnd);
        } else if (match[8]) {
        } else if (match[9] || match[10]) {
          const mathStart = matchStart + (match[9] ? 2 : 1);
          const mathEnd = matchStart + fullMatch.length - (match[9] ? 2 : 1);
          addRawText(mathStart, mathEnd);
        } else if (match[12] || match[13]) {
          const codeStart = matchStart + 1;
          const codeEnd = matchStart + fullMatch.length - 1;
          addRawText(codeStart, codeEnd);
        } else if (match[15]) {
          const charPos = matchStart + 1;
          map.push(charPos);
          strippedRaw += text[charPos];
        }
        lastIndex = tokenRegex.lastIndex;
      }
    } catch (e) {
      console.warn("tokenRegex execution failed in findCandidatesStripped (mobile backtracking limit):", e);
      return [];
    }
    for (let i = lastIndex; i < text.length; i++) {
      map.push(i);
      strippedRaw += text[i];
    }
    const patternSnippet = this.stripUrlsForPatternMatch(snippet.trim());
    const pattern = this.createFlexiblePattern(patternSnippet);
    if (!pattern) {
      return [];
    }
    let regex;
    try {
      regex = new RegExp(pattern, "gmu");
    } catch (e) {
      console.error("INVALID REGEX PATTERN in findCandidatesStripped:", e);
      return [];
    }
    const candidates = [];
    let strippedMatch;
    try {
      while ((strippedMatch = regex.exec(strippedRaw)) !== null) {
        const strippedStart = strippedMatch.index;
        const strippedEnd = strippedMatch.index + strippedMatch[0].length;
        const rawStart = map[strippedStart];
        const rawEnd = strippedEnd < map.length ? map[strippedEnd] : map[strippedEnd - 1] + 1;
        if (rawStart >= bodyStart) {
          candidates.push({
            start: rawStart,
            end: rawEnd,
            text: text.substring(rawStart, rawEnd)
          });
        }
      }
    } catch (e) {
      console.warn("Regex execution failed in findCandidatesStripped (mobile backtracking limit):", e);
      return [];
    }
    return candidates;
  }
  findBlockSequenceCandidates(text, selectionBlocks, bodyStart = 0) {
    if (selectionBlocks.length === 0) {
      return [];
    }
    const documentLines = this.createDocumentLineRecords(text);
    const candidates = [];
    for (let startIndex = 0; startIndex < documentLines.length; startIndex++) {
      const firstLine = documentLines[startIndex];
      if (firstLine.start < bodyStart || !this.lineMatches(firstLine.compare, selectionBlocks[0])) {
        continue;
      }
      let selectionIndex = 1;
      let docIndex = startIndex + 1;
      let lastMatch = startIndex;
      while (selectionIndex < selectionBlocks.length && docIndex < documentLines.length) {
        const candidateLine = documentLines[docIndex];
        if (this.lineMatches(candidateLine.compare, selectionBlocks[selectionIndex])) {
          lastMatch = docIndex;
          selectionIndex++;
          docIndex++;
          continue;
        }
        if (candidateLine.skippable) {
          docIndex++;
          continue;
        }
        break;
      }
      if (selectionIndex === selectionBlocks.length) {
        candidates.push({
          start: firstLine.start,
          end: documentLines[lastMatch].end,
          text: text.substring(firstLine.start, documentLines[lastMatch].end)
        });
      }
    }
    return this.dedupeCandidates(candidates);
  }
  createDocumentLineRecords(text) {
    const lines = [];
    let offset = 0;
    while (offset <= text.length) {
      const nextBreak = text.indexOf("\n", offset);
      const end = nextBreak === -1 ? text.length : nextBreak;
      const rawLine = text.substring(offset, end);
      const compare = this.normalizeLineForCompare(rawLine);
      lines.push({
        raw: rawLine,
        start: offset,
        end,
        compare,
        skippable: compare.length === 0 || MARKDOWN_PREFIX_ONLY_RE.test(rawLine.trimEnd())
      });
      if (nextBreak === -1) {
        break;
      }
      offset = nextBreak + 1;
    }
    return lines;
  }
  splitSelectionBlocks(snippet, filterEmpty = true) {
    const normalized = snippet.replace(/\r\n?/g, "\n");
    const blocks = normalized.split("\n").map((line) => this.normalizeComparableText(line));
    return filterEmpty ? blocks.filter((line) => line.length > 0) : blocks;
  }
  normalizeLineForCompare(line) {
    const strippedLine = line.replace(INLINE_DECORATION_RE, "");
    const parts = this.splitMarkdownLine(strippedLine);
    return this.normalizeComparableText(parts.content);
  }
  normalizeComparableText(text) {
    return this.stripBrowserJunk(text).replace(INLINE_DECORATION_RE, "").replace(/\s+/g, " ").trim();
  }
  splitMarkdownLine(line) {
    const indentMatch = line.match(/^\s*/);
    const indent = indentMatch ? indentMatch[0] : "";
    let remainder = line.substring(indent.length);
    let prefix = "";
    const prefixPatterns = [
      /^\[\^[^\]]+\]:\s*/,
      /^>\s*/,
      /^#{1,6}\s+/,
      /^-\s\[[ xX]\]\s+/,
      /^[-*+]\s+/,
      /^\d{1,3}[.)]\s+/
    ];
    let matched = true;
    while (matched && remainder) {
      matched = false;
      for (const pattern of prefixPatterns) {
        const match = remainder.match(pattern);
        if (match) {
          prefix += match[0];
          remainder = remainder.substring(match[0].length);
          matched = true;
          break;
        }
      }
    }
    return { indent, prefix, content: remainder };
  }
  lineMatches(source, target) {
    if (!source || !target) {
      return false;
    }
    if (source === target) {
      return true;
    }
    if (source.includes(target) || target.includes(source)) {
      return true;
    }
    const fuzzySource = this.normalizeForFuzzySearch(source);
    const fuzzyTarget = this.normalizeForFuzzySearch(target);
    if (!fuzzySource || !fuzzyTarget) {
      return false;
    }
    return fuzzySource === fuzzyTarget || fuzzySource.includes(fuzzyTarget) || fuzzyTarget.includes(fuzzySource);
  }
  findFuzzyCandidates(text, snippet, bodyStart = 0) {
    const needle = this.normalizeForFuzzySearch(snippet);
    if (!needle) {
      return [];
    }
    const { normalized, map } = this.buildFuzzyMap(text);
    if (!normalized) {
      return [];
    }
    const candidates = [];
    let fromIndex = 0;
    while (fromIndex < normalized.length) {
      const matchIndex = normalized.indexOf(needle, fromIndex);
      if (matchIndex === -1) {
        break;
      }
      const rawStart = map[matchIndex];
      const rawEnd = map[matchIndex + needle.length - 1] + 1;
      if (rawStart >= bodyStart) {
        candidates.push({
          start: rawStart,
          end: rawEnd,
          text: text.substring(rawStart, rawEnd)
        });
      }
      fromIndex = matchIndex + 1;
    }
    return this.dedupeCandidates(candidates);
  }
  buildFuzzyMap(text) {
    let normalized = "";
    const map = [];
    for (let i = 0; i < text.length; i++) {
      const char = text[i];
      if (/[\p{L}\p{N}]/u.test(char)) {
        normalized += char.toLocaleLowerCase();
        map.push(i);
      }
    }
    return { normalized, map };
  }
  normalizeForFuzzySearch(text) {
    return this.normalizeComparableText(text).split("").filter((char) => /[\p{L}\p{N}]/u.test(char)).join("").toLocaleLowerCase();
  }
  dedupeCandidates(candidates) {
    const seen = /* @__PURE__ */ new Set();
    return candidates.filter((candidate) => {
      const key = `${candidate.start}:${candidate.end}`;
      if (seen.has(key)) {
        return false;
      }
      seen.add(key);
      return true;
    });
  }
  offsetCandidates(candidates, offset) {
    return candidates.map((candidate) => ({
      ...candidate,
      start: candidate.start + offset,
      end: candidate.end + offset
    }));
  }
  calculateSimilarity(source, target) {
    if (source === target)
      return 1e3;
    const sSet = new Set(source.split(" "));
    const tSet = new Set(target.split(" "));
    let intersection = 0;
    for (const token of tSet) {
      if (sSet.has(token))
        intersection++;
    }
    const union = (/* @__PURE__ */ new Set([...sSet, ...tSet])).size;
    const jaccard = union === 0 ? 0 : intersection / union;
    const lenMultiplier = 1 / (1 + Math.abs(source.length - target.length) * 0.1);
    return jaccard * 0.7 + lenMultiplier * 0.3;
  }
};

// src/modals/TagSuggestModal.js
var import_obsidian2 = require("obsidian");
var TagSuggestModal = class extends import_obsidian2.Modal {
  constructor(plugin, onChoose) {
    super(plugin.app);
    this.plugin = plugin;
    this.onChoose = onChoose;
    this.selectedTags = /* @__PURE__ */ new Set();
    this.suggestions = [];
    this.query = "";
    this.suggestionEl = null;
    this.selectedContainer = null;
    this.smartSuggestionEl = null;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.addClass("reading-highlighter-tag-modal");
    modalEl.addClass("reading-highlighter-tag-modal");
    contentEl.createEl("h2", { text: "Add Tags" });
    if (this.plugin.settings.enableSmartTagSuggestions) {
      const smartTags = this.getSuggestedTags();
      if (smartTags.length > 0) {
        this.smartSuggestionEl = contentEl.createDiv({ cls: "smart-suggestions-container" });
        this.smartSuggestionEl.createEl("span", { text: "Suggestions: ", cls: "smart-suggestions-label" });
        const chipsContainer = this.smartSuggestionEl.createDiv({ cls: "smart-suggestions-chips" });
        smartTags.forEach((tag) => {
          const chip = chipsContainer.createEl("button", {
            text: `#${tag}`,
            cls: "smart-suggestion-chip"
          });
          chip.onclick = () => {
            this.toggleTag(tag);
            chip.addClass("selected");
          };
        });
      }
    }
    this.selectedContainer = contentEl.createDiv({ cls: "selected-tags-container" });
    this.updateSelectedView();
    const inputContainer = contentEl.createDiv({ cls: "tag-search-input-container" });
    const input = inputContainer.createEl("input", {
      type: "text",
      cls: "tag-search-input",
      attr: { placeholder: "Search or create tag..." }
    });
    const doneBtn = inputContainer.createEl("button", { text: "Done", cls: "mod-cta tag-done-btn" });
    setTimeout(() => input.focus(), 50);
    this.suggestionEl = contentEl.createDiv({ cls: "tag-suggestions-list" });
    doneBtn.onclick = () => this.submit();
    const tagCounts = this.app.metadataCache.getTags();
    this.allTags = Object.keys(tagCounts).map((t) => t.substring(1));
    input.addEventListener("input", (e) => {
      this.query = e.target.value;
      this.renderSuggestions(this.query);
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        if (this.query.trim()) {
          this.toggleTag(this.query.trim());
          this.query = "";
          input.value = "";
          this.renderSuggestions("");
        }
      } else if (e.key === "Escape") {
        this.close();
      }
    });
    this.renderSuggestions("");
  }
  /**
   * Get smart tag suggestions based on:
   * 1. Recent tags (MRU)
   * 2. Current folder name
   * 3. Frontmatter tags
   */
  getSuggestedTags() {
    var _a, _b;
    const suggestions = [];
    const activeFile = this.app.workspace.getActiveFile();
    if (((_a = activeFile == null ? void 0 : activeFile.parent) == null ? void 0 : _a.name) && activeFile.parent.name !== "/") {
      const folderTag = activeFile.parent.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-_]/g, "");
      if (folderTag && !suggestions.includes(folderTag)) {
        suggestions.push(folderTag);
      }
    }
    if (activeFile) {
      const cache = this.app.metadataCache.getFileCache(activeFile);
      if ((_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.tags) {
        const fmTags = Array.isArray(cache.frontmatter.tags) ? cache.frontmatter.tags : [cache.frontmatter.tags];
        fmTags.forEach((tag) => {
          const cleanTag = String(tag).replace(/^#/, "");
          if (cleanTag && !suggestions.includes(cleanTag)) {
            suggestions.push(cleanTag);
          }
        });
      }
    }
    return [...new Set(suggestions)].slice(0, 8);
  }
  renderSuggestions(query) {
    this.suggestionEl.empty();
    const cleanQuery = query.toLowerCase().replace(/\s+/g, "_");
    let matches = this.allTags.filter((t) => t.toLowerCase().includes(cleanQuery));
    const isExact = matches.some((t) => t.toLowerCase() === cleanQuery);
    if (cleanQuery && !isExact) {
      this.renderItem(cleanQuery, true);
    }
    matches.slice(0, 50).forEach((tag) => {
      if (!this.selectedTags.has(tag)) {
        this.renderItem(tag, false);
      }
    });
  }
  renderItem(tag, isNew) {
    const el = this.suggestionEl.createDiv({ cls: "suggestion-item" });
    el.createSpan({ text: isNew ? `#${tag}` : `#${tag}` });
    if (isNew) {
      el.createSpan({ text: " (Create new)", cls: "suggestion-note" });
    }
    el.addEventListener("click", () => {
      this.toggleTag(tag);
      this.query = "";
      this.contentEl.querySelector(".tag-search-input").value = "";
      this.contentEl.querySelector(".tag-search-input").focus();
      this.renderSuggestions("");
    });
  }
  toggleTag(tag) {
    const cleanTag = tag.replace(/^#/, "").replace(/\s+/g, "_");
    if (this.selectedTags.has(cleanTag)) {
      this.selectedTags.delete(cleanTag);
    } else {
      this.selectedTags.add(cleanTag);
    }
    this.updateSelectedView();
  }
  updateSelectedView() {
    this.selectedContainer.empty();
    if (this.selectedTags.size === 0) {
      this.selectedContainer.createSpan({
        text: "No tags selected",
        cls: "no-tags-hint"
      });
      return;
    }
    this.selectedTags.forEach((tag) => {
      const chip = this.selectedContainer.createDiv({ cls: "tag-chip" });
      chip.createSpan({ text: `#${tag}` });
      const close = chip.createSpan({ cls: "tag-chip-close", text: "\xD7" });
      close.onclick = (e) => {
        e.stopPropagation();
        this.toggleTag(tag);
      };
    });
  }
  submit() {
    const result = Array.from(this.selectedTags).map((t) => `#${t}`).join(" ");
    this.onChoose(result);
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/modals/AnnotationModal.js
var import_obsidian3 = require("obsidian");
var AnnotationModal = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.comment = "";
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("reading-highlighter-annotation-modal");
    if (this.containerEl) {
      this.containerEl.addClass("reading-highlighter-modal-container");
    }
    contentEl.createEl("h2", { text: "Add Annotation" });
    contentEl.createEl("p", {
      text: "Your comment will be added as a footnote at the bottom of the document.",
      cls: "annotation-description"
    });
    const textArea = new import_obsidian3.TextAreaComponent(contentEl);
    textArea.inputEl.addClass("annotation-textarea");
    textArea.setPlaceholder("Enter your annotation...");
    textArea.onChange((value) => {
      this.comment = value;
    });
    setTimeout(() => textArea.inputEl.focus(), 50);
    textArea.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit();
      }
    });
    const footer = contentEl.createDiv({ cls: "modal-footer" });
    const cancelBtn = footer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const submitBtn = footer.createEl("button", { text: "Add Annotation", cls: "mod-cta" });
    submitBtn.onclick = () => this.submit();
  }
  submit() {
    if (this.comment.trim()) {
      this.onSubmit(this.comment.trim());
    }
    this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/HighlightNavigator.js
var import_obsidian4 = require("obsidian");
init_export();
var HIGHLIGHT_NAVIGATOR_VIEW = "highlight-navigator";
var HighlightNavigatorView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.highlights = [];
    this.footnotes = [];
    this.currentFile = null;
    this.viewMode = "highlights";
  }
  getViewType() {
    return HIGHLIGHT_NAVIGATOR_VIEW;
  }
  getDisplayText() {
    return "Highlights";
  }
  getIcon() {
    return "highlighter";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("highlight-navigator-container");
    const header = container.createDiv({ cls: "highlight-navigator-header" });
    header.createEl("h4", { text: "Navigator" });
    const btnGroup = header.createDiv({ cls: "highlight-navigator-btn-group" });
    const modes = [
      { label: "Highlights", value: "highlights" },
      { label: "Footnotes", value: "footnotes" },
      { label: "Both", value: "split" }
    ];
    modes.forEach((m) => {
      const btn = btnGroup.createEl("button", { text: m.label, cls: "nav-btn" });
      if (this.viewMode === m.value)
        btn.addClass("is-active");
      btn.onclick = () => {
        btnGroup.querySelectorAll(".nav-btn").forEach((el) => el.removeClass("is-active"));
        btn.addClass("is-active");
        this.viewMode = m.value;
        this.renderContent();
      };
    });
    this.contentEl = container.createDiv({ cls: "highlight-navigator-content" });
    const footer = container.createDiv({ cls: "highlight-navigator-footer" });
    const exportBtn = footer.createEl("button", { text: "Export to MD", cls: "mod-cta" });
    exportBtn.onclick = () => this.exportHighlights();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.refresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.currentFile && file.path === this.currentFile.path) {
          this.refresh(true);
        }
      })
    );
    this.refresh();
  }
  async refresh(force = false) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!view || !view.file) {
      return;
    }
    if (!force && this.currentFile && view.file.path === this.currentFile.path) {
      return;
    }
    this.currentFile = view.file;
    try {
      const raw = await this.app.vault.read(view.file);
      this.highlights = getHighlightsFromContent(raw);
      this.footnotes = this.getFootnotesFromContent(raw);
      this.renderContent();
    } catch (err) {
      this.showEmpty("Error loading content.");
      console.error(err);
    }
  }
  getFootnotesFromContent(raw) {
    const footnotes = [];
    const lines = raw.split("\n");
    const pattern = /\[\^([^\]]+)\]:\s*([^\n]+)/g;
    lines.forEach((line, lineIdx) => {
      let match;
      while ((match = pattern.exec(line)) !== null) {
        footnotes.push({
          id: match[1],
          text: match[2].trim(),
          line: lineIdx
        });
      }
    });
    return footnotes;
  }
  showEmpty(message, container = this.contentEl) {
    container.empty();
    container.createDiv({ cls: "highlight-navigator-empty", text: message });
  }
  renderContent() {
    this.contentEl.empty();
    this.contentEl.removeClass("split-view");
    if (this.viewMode === "highlights") {
      this.renderList(this.contentEl, this.highlights, "highlights");
    } else if (this.viewMode === "footnotes") {
      this.renderList(this.contentEl, this.footnotes, "footnotes");
    } else if (this.viewMode === "split") {
      this.contentEl.addClass("split-view");
      const topHalf = this.contentEl.createDiv({ cls: "split-half split-top" });
      const bottomHalf = this.contentEl.createDiv({ cls: "split-half split-bottom" });
      this.renderList(topHalf, this.highlights, "highlights");
      this.renderList(bottomHalf, this.footnotes, "footnotes");
    }
  }
  renderList(container, items, type) {
    if (items.length === 0) {
      this.showEmpty(`No ${type} found.`, container);
      return;
    }
    const title = type === "highlights" ? "Highlights" : "Footnotes";
    const stats = container.createDiv({ cls: "highlight-navigator-stats" });
    stats.createSpan({ text: `${items.length} ${title.toLowerCase()}` });
    const list = container.createDiv({ cls: "highlight-navigator-list" });
    const fragment = document.createDocumentFragment();
    items.forEach((item, index) => {
      const el = document.createElement("div");
      el.addClass("highlight-navigator-item");
      if (type === "highlights") {
        if (item.color) {
          const colorDot = document.createElement("span");
          colorDot.addClass("highlight-color-dot");
          colorDot.style.backgroundColor = item.color;
          el.appendChild(colorDot);
        } else {
          const colorDot = document.createElement("span");
          colorDot.addClass("highlight-color-dot", "highlight-default");
          el.appendChild(colorDot);
        }
      } else {
        const idSpan = document.createElement("span");
        idSpan.addClass("footnote-id");
        idSpan.textContent = `[${item.id}] `;
        idSpan.style.marginRight = "5px";
        idSpan.style.color = "var(--text-muted)";
        el.appendChild(idSpan);
      }
      const textPreview = item.text.length > 80 ? item.text.substring(0, 80) + "..." : item.text;
      const textSpan = document.createElement("span");
      textSpan.addClass("highlight-text");
      textSpan.textContent = textPreview;
      el.appendChild(textSpan);
      if (type === "highlights") {
        const numberBadge = document.createElement("span");
        numberBadge.addClass("highlight-number");
        numberBadge.textContent = `${index + 1}`;
        el.appendChild(numberBadge);
      }
      el.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.jumpToLine(item.line);
      };
      fragment.appendChild(el);
    });
    list.appendChild(fragment);
  }
  async jumpToLine(line) {
    const leaf = this.app.workspace.getMostRecentLeaf();
    if (leaf && leaf.view instanceof import_obsidian4.MarkdownView) {
      leaf.setEphemeralState({
        line,
        focus: true
      });
    }
  }
  async exportHighlights() {
    if (!this.currentFile)
      return;
    try {
      const { exportHighlightsToMD: exportHighlightsToMD2 } = await Promise.resolve().then(() => (init_export(), export_exports));
      const exportPath = await exportHighlightsToMD2(this.app, this.currentFile);
      const exportFile = this.app.vault.getAbstractFileByPath(exportPath);
      if (exportFile) {
        await this.app.workspace.getLeaf().openFile(exportFile);
      }
    } catch (err) {
      console.error(err);
    }
  }
  async onClose() {
  }
};

// src/utils/dom.js
function getScroll(view) {
  var _a;
  return typeof ((_a = view.previewMode) == null ? void 0 : _a.getScroll) === "function" ? view.previewMode.getScroll() : getFallbackScroll(view);
}
function applyScroll(view, pos) {
  var _a;
  if (typeof ((_a = view.previewMode) == null ? void 0 : _a.applyScroll) === "function") {
    view.previewMode.applyScroll(pos);
  } else {
    setFallbackScroll(view, pos);
  }
}
function getFallbackScroll(view) {
  var _a, _b;
  const el = (_a = view.containerEl.querySelector(".markdown-reading-view")) != null ? _a : view.containerEl.querySelector(".markdown-preview-view");
  return { x: 0, y: (_b = el == null ? void 0 : el.scrollTop) != null ? _b : 0 };
}
function setFallbackScroll(view, { y }) {
  var _a;
  const el = (_a = view.containerEl.querySelector(".markdown-reading-view")) != null ? _a : view.containerEl.querySelector(".markdown-preview-view");
  if (el)
    el.scrollTop = y;
}

// src/main.js
init_export();
var SMART_SELECTION_TAGS = /* @__PURE__ */ new Set([
  "P",
  "LI",
  "BLOCKQUOTE",
  "PRE",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "TD",
  "TH"
]);
var FRONTMATTER_NEEDS_QUOTES_RE = new RegExp("[:\\s{}\\[\\],&*#?|<>=!%@\\\\-]");
var FRONTMATTER_RESERVED_RE = /^(true|false|null|yes|no|on|off)$/i;
var DEFAULT_SETTINGS = {
  toolbarPosition: "right",
  enableColorHighlighting: false,
  highlightColor: "",
  defaultTagPrefix: "",
  enableHaptics: true,
  showTagButton: true,
  showRemoveButton: true,
  showQuoteButton: true,
  // NEW: Color Palette (optional, disabled by default = use == highlight)
  enableColorPalette: false,
  colorPalette: [
    { name: "Yellow", color: "#FFEE58", tag: "" },
    { name: "Blue", color: "#64B5F6", tag: "" },
    { name: "Green", color: "#81C784", tag: "" },
    { name: "Red", color: "#EF5350", tag: "" },
    { name: "Purple", color: "#BA68C8", tag: "" }
  ],
  // NEW: Highlight Styles (presets with color + tag)
  highlightStyles: [
    { name: "Important", color: "#FFEE58", tag: "important" },
    { name: "Question", color: "#64B5F6", tag: "question" },
    { name: "Definition", color: "#81C784", tag: "definition" }
  ],
  // NEW: Quote Template
  quoteTemplate: "> {{text}}\n>\n> \u2014 [[{{file}}]]",
  // NEW: Annotations
  enableAnnotations: true,
  showAnnotationButton: true,
  // NEW: Reading Progress
  enableReadingProgress: true,
  readingPositions: {},
  // NEW: Smart Tags
  enableSmartTagSuggestions: true,
  recentTags: [],
  maxRecentTags: 10,
  // NEW: Navigator
  showNavigatorButton: true,
  // NEW: Tooltips (disabled by default)
  showTooltips: false,
  // NEW: Frontmatter Auto-Tag
  enableFrontmatterTag: false,
  frontmatterTag: "resaltados",
  // NEW: Smart paragraph snapping
  enableSmartParagraphSelection: false
};
var ReadingHighlighterPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.floatingManager = new FloatingManager(this);
    this.logic = new SelectionLogic(this.app);
    this.lastModification = null;
    this.lastScrollPosition = null;
    this.registerView(
      HIGHLIGHT_NAVIGATOR_VIEW,
      (leaf) => new HighlightNavigatorView(leaf, this)
    );
    this.addSettingTab(new ReadingHighlighterSettingTab(this.app, this));
    this.registerCommands();
    this.registerDomEvent(document, "selectionchange", () => {
      this.floatingManager.handleSelection();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.floatingManager.handleSelection();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (_leaf) => {
        if (this.settings.enableReadingProgress) {
          this.saveReadingProgress();
        }
      })
    );
    if (import_obsidian5.Platform.isMobile) {
      const btn = this.addRibbonIcon("highlighter", "Highlight Selection", () => {
        const view = this.getActiveReadingView();
        if (view)
          this.highlightSelection(view);
        else
          new import_obsidian5.Notice("Open a note in Reading View first.");
      });
      this.register(() => btn.remove());
    }
    this.addRibbonIcon("list", "Highlight Navigator", () => {
      this.activateNavigatorView();
    });
    this.floatingManager.load();
  }
  registerCommands() {
    this.addCommand({
      id: "highlight-selection-reading",
      name: "Highlight selection (Reading View)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.highlightSelection(view);
        return true;
      }
    });
    this.addCommand({
      id: "tag-selection",
      name: "Tag selection (Reading View)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.tagSelection(view);
        return true;
      }
    });
    this.addCommand({
      id: "annotate-selection",
      name: "Add annotation to selection (Reading View)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.annotateSelection(view);
        return true;
      }
    });
    this.addCommand({
      id: "copy-as-quote",
      name: "Copy selection as quote (Reading View)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.copyAsQuote(view);
        return true;
      }
    });
    this.addCommand({
      id: "remove-highlight",
      name: "Remove highlight from selection (Reading View)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.removeHighlightSelection(view);
        return true;
      }
    });
    this.addCommand({
      id: "undo-last-highlight",
      name: "Undo last highlight",
      callback: () => {
        this.undoLastHighlight();
      }
    });
    this.addCommand({
      id: "open-highlight-navigator",
      name: "Open highlight navigator",
      callback: () => {
        this.activateNavigatorView();
      }
    });
    this.addCommand({
      id: "export-highlights",
      name: "Export highlights to new note",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.exportHighlights(view);
        return true;
      }
    });
    this.addCommand({
      id: "remove-all-highlights",
      name: "Remove all highlights from note",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.removeAllHighlights(view);
        return true;
      }
    });
    this.addCommand({
      id: "resume-reading",
      name: "Resume reading (jump to last position)",
      checkCallback: (checking) => {
        const view = this.getActiveReadingView();
        if (!view)
          return false;
        if (checking)
          return true;
        this.resumeReading(view);
        return true;
      }
    });
    for (let i = 0; i < 5; i++) {
      this.addCommand({
        id: `apply-color-${i + 1}`,
        name: `Apply highlight color ${i + 1}`,
        checkCallback: (checking) => {
          if (!this.settings.enableColorPalette)
            return false;
          const view = this.getActiveReadingView();
          if (!view)
            return false;
          if (checking)
            return true;
          this.applyColorByIndex(view, i);
          return true;
        }
      });
    }
  }
  onunload() {
    this.floatingManager.unload();
    this.app.workspace.detachLeavesOfType(HIGHLIGHT_NAVIGATOR_VIEW);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.floatingManager.refresh();
  }
  getActiveReadingView() {
    const view = this.app.workspace.getActiveViewOfType(require("obsidian").MarkdownView);
    return view && view.getMode() === "preview" ? view : null;
  }
  getSelectionContext(selectionSnapshot) {
    var _a;
    const view = this.getActiveReadingView();
    const range = this.getSelectionRange(selectionSnapshot);
    if (!view || !range)
      return null;
    const blocks = this.getAllowedBlocksInRange(range, view.contentEl);
    const fallbackBlock = this.getClosestAllowedBlock(range.commonAncestorContainer, view.contentEl);
    const contextElement = blocks[0] || fallbackBlock || null;
    const rawSnippet = (selectionSnapshot == null ? void 0 : selectionSnapshot.text) || ((_a = window.getSelection()) == null ? void 0 : _a.toString()) || "";
    let snippet = rawSnippet;
    if (this.settings.enableSmartParagraphSelection && blocks.length === 1) {
      const blockText = this.getElementText(blocks[0]);
      if (blockText) {
        snippet = blockText;
      }
    }
    return {
      element: contextElement,
      blocks,
      snippet,
      text: contextElement ? this.getElementText(contextElement) : null
    };
  }
  getSelectionRange(selectionSnapshot) {
    if (selectionSnapshot == null ? void 0 : selectionSnapshot.range) {
      return selectionSnapshot.range.cloneRange();
    }
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) {
      return null;
    }
    return selection.getRangeAt(0).cloneRange();
  }
  getAllowedBlocksInRange(range, root) {
    if (!root)
      return [];
    const selector = Array.from(SMART_SELECTION_TAGS).map((tag) => tag.toLowerCase()).join(", ");
    const blocks = Array.from(root.querySelectorAll(selector)).filter((element) => {
      const text = this.getElementText(element);
      if (!text)
        return false;
      try {
        return range.intersectsNode(element);
      } catch (_error) {
        return false;
      }
    });
    return blocks.filter((element) => !blocks.some((other) => other !== element && other.contains(element)));
  }
  getClosestAllowedBlock(node, root) {
    let current = (node == null ? void 0 : node.nodeType) === Node.ELEMENT_NODE ? node : node == null ? void 0 : node.parentElement;
    while (current && current !== root) {
      if (SMART_SELECTION_TAGS.has(current.tagName) && this.getElementText(current)) {
        return current;
      }
      current = current.parentElement;
    }
    return current && SMART_SELECTION_TAGS.has(current.tagName) ? current : null;
  }
  getElementText(element) {
    return ((element == null ? void 0 : element.innerText) || (element == null ? void 0 : element.textContent) || "").replace(/\s+/g, " ").trim();
  }
  buildSelectionRequest(view, selectionSnapshot) {
    const sel = window.getSelection();
    const selectionContext = this.getSelectionContext(selectionSnapshot);
    const snippet = (selectionContext == null ? void 0 : selectionContext.snippet) || (selectionSnapshot == null ? void 0 : selectionSnapshot.text) || (sel == null ? void 0 : sel.toString()) || "";
    if (!snippet.trim()) {
      return null;
    }
    const contextElement = (selectionContext == null ? void 0 : selectionContext.element) || null;
    return {
      snippet,
      contextElement,
      contextText: contextElement ? this.getElementText(contextElement) : null,
      occurrenceIndex: this.getSelectionOccurrence(view, contextElement)
    };
  }
  getSelectionOccurrence(view, contextElement) {
    if (!contextElement)
      return 0;
    const contextText = contextElement.innerText.trim();
    const tagName = contextElement.tagName.toLowerCase();
    const allElements = view.contentEl.querySelectorAll(tagName);
    let count = 0;
    let foundIndex = 0;
    for (let i = 0; i < allElements.length; i++) {
      const el = allElements[i];
      if (el.innerText.trim() === contextText) {
        if (el === contextElement) {
          foundIndex = count;
          break;
        }
        count++;
      }
    }
    return foundIndex;
  }
  // Save state for undo
  async saveUndoState(file) {
    this.lastModification = {
      file,
      original: await this.app.vault.read(file)
    };
  }
  // Undo last highlight
  async undoLastHighlight() {
    if (!this.lastModification) {
      new import_obsidian5.Notice("Nothing to undo.");
      return;
    }
    try {
      await this.app.vault.modify(
        this.lastModification.file,
        this.lastModification.original
      );
      new import_obsidian5.Notice("Undone last highlight.");
      this.lastModification = null;
    } catch (err) {
      new import_obsidian5.Notice("Failed to undo.");
      console.error(err);
    }
  }
  async highlightSelection(view, selectionSnapshot) {
    var _a;
    const sel = window.getSelection();
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request) {
      new import_obsidian5.Notice("No text selected.");
      return;
    }
    const scrollPos = getScroll(view);
    await this.saveUndoState(view.file);
    const result = await this.logic.locateSelection(
      view.file,
      view,
      request.snippet,
      request.contextText,
      request.occurrenceIndex
    );
    if (!result) {
      new import_obsidian5.Notice("Could not locate selection in file.");
      return;
    }
    const targetFile = result.file;
    await this.saveUndoState(targetFile);
    let mode = "highlight";
    let payload = "";
    if (this.settings.enableColorHighlighting && this.settings.highlightColor) {
      mode = "color";
      payload = this.settings.highlightColor;
    }
    await this.applyMarkdownModification(targetFile, "", result.start, result.end, mode, payload);
    this.restoreScroll(view, scrollPos);
    sel == null ? void 0 : sel.removeAllRanges();
    if (this.settings.enableHaptics && import_obsidian5.Platform.isMobile) {
      (_a = navigator.vibrate) == null ? void 0 : _a.call(navigator, 10);
    }
    new import_obsidian5.Notice("Highlighted!");
  }
  // Apply color by palette index
  async applyColorByIndex(view, index, selectionSnapshot) {
    if (index < 0 || index >= this.settings.colorPalette.length)
      return;
    const palette = this.settings.colorPalette[index];
    await this.applyColorHighlight(view, palette.color, palette.tag, selectionSnapshot);
  }
  async tagSelection(view, selectionSnapshot) {
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request) {
      new import_obsidian5.Notice("No text selected.");
      return;
    }
    const scrollPos = getScroll(view);
    await this.saveUndoState(view.file);
    const result = await this.logic.locateSelection(
      view.file,
      view,
      request.snippet,
      request.contextText,
      request.occurrenceIndex
    );
    if (!result) {
      new import_obsidian5.Notice("Could not locate selection in file.");
      return;
    }
    const targetFile = result.file;
    await this.saveUndoState(targetFile);
    new TagSuggestModal(this, async (tag) => {
      var _a;
      if (tag && this.settings.enableSmartTagSuggestions) {
        this.addRecentTag(tag);
      }
      await this.applyMarkdownModification(targetFile, "", result.start, result.end, "tag", tag);
      this.restoreScroll(view, scrollPos);
      (_a = window.getSelection()) == null ? void 0 : _a.removeAllRanges();
    }).open();
  }
  // Add to recent tags
  addRecentTag(tag) {
    const cleanTag = tag.replace(/^#/, "").trim();
    if (!cleanTag)
      return;
    this.settings.recentTags = this.settings.recentTags.filter((t) => t !== cleanTag);
    this.settings.recentTags.unshift(cleanTag);
    if (this.settings.recentTags.length > this.settings.maxRecentTags) {
      this.settings.recentTags = this.settings.recentTags.slice(0, this.settings.maxRecentTags);
    }
    this.saveSettings();
  }
  // Annotate selection with footnote
  async annotateSelection(view, selectionSnapshot) {
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request) {
      new import_obsidian5.Notice("No text selected.");
      return;
    }
    const scrollPos = getScroll(view);
    const result = await this.logic.locateSelection(
      view.file,
      view,
      request.snippet,
      request.contextText,
      request.occurrenceIndex
    );
    if (!result) {
      new import_obsidian5.Notice("Could not locate selection in file.");
      return;
    }
    const targetFile = result.file;
    await this.saveUndoState(targetFile);
    new AnnotationModal(this.app, async (comment) => {
      var _a;
      const currentRaw = await this.app.vault.read(targetFile);
      await this.applyAnnotation(targetFile, currentRaw, result.start, result.end, comment);
      this.restoreScroll(view, scrollPos);
      (_a = window.getSelection()) == null ? void 0 : _a.removeAllRanges();
      new import_obsidian5.Notice("Annotation added!");
    }).open();
  }
  // Apply annotation as footnote
  async applyAnnotation(file, raw, start, end, comment) {
    if (!raw) {
      raw = await this.app.vault.read(file);
    }
    const footnotePattern = /\[\^(\d+)\]/g;
    let maxNumber = 0;
    let match;
    while ((match = footnotePattern.exec(raw)) !== null) {
      const num = parseInt(match[1]);
      if (num > maxNumber)
        maxNumber = num;
    }
    const footnoteNum = maxNumber + 1;
    const beforeSelection = raw.substring(0, end);
    const afterSelection = raw.substring(end);
    const footnoteRef = `[^${footnoteNum}]`;
    const footnoteDef = `

[^${footnoteNum}]: ${comment}`;
    let newContent = beforeSelection + footnoteRef + afterSelection;
    newContent = newContent.trimEnd() + footnoteDef + "\n";
    await this.app.vault.modify(file, newContent);
  }
  async removeHighlightSelection(view, selectionSnapshot) {
    const sel = window.getSelection();
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request) {
      new import_obsidian5.Notice("Select highlighted text to remove.");
      return;
    }
    const scrollPos = getScroll(view);
    await this.saveUndoState(view.file);
    const result = await this.logic.locateSelection(
      view.file,
      view,
      request.snippet,
      request.contextText,
      request.occurrenceIndex
    );
    if (!result) {
      new import_obsidian5.Notice("Could not locate selection in file.");
      return;
    }
    const targetFile = result.file;
    await this.saveUndoState(targetFile);
    await this.applyMarkdownModification(targetFile, "", result.start, result.end, "remove");
    new import_obsidian5.Notice("Highlighting removed.");
    this.restoreScroll(view, scrollPos);
    sel == null ? void 0 : sel.removeAllRanges();
  }
  // Remove all highlights from file
  async removeAllHighlights(view) {
    await this.saveUndoState(view.file);
    let raw = await this.app.vault.read(view.file);
    raw = raw.replace(/==(.*?)==/g, "$1");
    raw = raw.replace(/<mark[^>]*>(.*?)<\/mark>/g, "$1");
    await this.app.vault.modify(view.file, raw);
    new import_obsidian5.Notice("All highlights removed.");
  }
  // Export highlights to new MD file
  async exportHighlights(view) {
    try {
      const exportPath = await exportHighlightsToMD(this.app, view.file);
      new import_obsidian5.Notice(`Highlights exported to ${exportPath}`);
      const exportFile = this.app.vault.getAbstractFileByPath(exportPath);
      if (exportFile) {
        await this.app.workspace.getLeaf().openFile(exportFile);
      }
    } catch (err) {
      new import_obsidian5.Notice("Failed to export highlights.");
      console.error(err);
    }
  }
  async copyAsQuote(view, selectionSnapshot) {
    var _a;
    const sel = window.getSelection();
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request) {
      new import_obsidian5.Notice("No text selected.");
      return;
    }
    const quotedText = request.snippet.split(/\r?\n/).map((line) => `> ${line}`).join("\n");
    const frontmatter = ((_a = this.app.metadataCache.getFileCache(view.file)) == null ? void 0 : _a.frontmatter) || {};
    const quote = this.expandQuoteTemplate(view.file, quotedText, frontmatter);
    const copied = await this.writeClipboardText(quote);
    if (!copied) {
      new import_obsidian5.Notice("Failed to copy quote.");
      return;
    }
    new import_obsidian5.Notice("Copied as quote!");
    sel == null ? void 0 : sel.removeAllRanges();
  }
  async applyColorHighlight(view, color, autoTag = "", selectionSnapshot) {
    const sel = window.getSelection();
    const request = this.buildSelectionRequest(view, selectionSnapshot);
    if (!request)
      return;
    const scrollPos = getScroll(view);
    await this.saveUndoState(view.file);
    const result = await this.logic.locateSelection(
      view.file,
      view,
      request.snippet,
      request.contextText,
      request.occurrenceIndex
    );
    if (!result) {
      new import_obsidian5.Notice("Could not locate selection.");
      return;
    }
    const targetFile = result.file;
    await this.saveUndoState(targetFile);
    await this.applyMarkdownModification(targetFile, result.raw, result.start, result.end, "color", color, autoTag);
    this.restoreScroll(view, scrollPos);
    sel == null ? void 0 : sel.removeAllRanges();
    new import_obsidian5.Notice("Highlighted!");
  }
  // Reading progress
  saveReadingProgress() {
    const view = this.getActiveReadingView();
    if (!view || !view.file)
      return;
    const pos = getScroll(view);
    if (pos && pos.y > 0) {
      this.settings.readingPositions[view.file.path] = pos.y;
      this.saveSettings();
    }
  }
  async resumeReading(view) {
    const pos = this.settings.readingPositions[view.file.path];
    if (pos) {
      applyScroll(view, { y: pos });
      new import_obsidian5.Notice("Resumed reading position.");
    } else {
      new import_obsidian5.Notice("No saved position for this file.");
    }
  }
  // Activate navigator view
  async activateNavigatorView() {
    const existing = this.app.workspace.getLeavesOfType(HIGHLIGHT_NAVIGATOR_VIEW);
    if (existing.length) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({
      type: HIGHLIGHT_NAVIGATOR_VIEW,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
  expandQuoteTemplate(file, quotedText, frontmatter = {}) {
    const sourceUrl = String(frontmatter.url || frontmatter.source || frontmatter.link || "").replace(/#:~:text=[^&]+(&|$)/, "");
    const timestamp = this.formatTimestamp(/* @__PURE__ */ new Date());
    const variables = {
      text: quotedText,
      file: file.basename,
      path: file.path,
      date: timestamp.split("T")[0],
      time: timestamp,
      domain: this.extractDomain(sourceUrl),
      author: this.normalizeFrontmatterValue(frontmatter.author || frontmatter.authors || frontmatter.creator || "")
    };
    return this.settings.quoteTemplate.replace(/{{(text|file|path|date|time|domain|author)}}/g, (_, key) => variables[key] || "");
  }
  async writeClipboardText(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (_error) {
      const textArea = document.createElement("textarea");
      textArea.value = text;
      textArea.style.position = "fixed";
      textArea.style.opacity = "0";
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      let copied = false;
      try {
        copied = document.execCommand("copy");
      } catch (_fallbackError) {
        copied = false;
      }
      textArea.remove();
      return copied;
    }
  }
  formatTimestamp(date) {
    const pad = (value) => String(Math.trunc(Math.abs(value))).padStart(2, "0");
    const offsetMinutes = -date.getTimezoneOffset();
    const sign = offsetMinutes >= 0 ? "+" : "-";
    const offsetHours = pad(offsetMinutes / 60);
    const offsetRemainder = pad(offsetMinutes % 60);
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}${sign}${offsetHours}:${offsetRemainder}`;
  }
  extractDomain(url) {
    if (!url)
      return "";
    try {
      const parsed = new URL(url);
      const hostname = parsed.hostname;
      if (hostname === "localhost" || hostname === "127.0.0.1" || /^(\d{1,3}\.){3}\d{1,3}$/.test(hostname)) {
        return hostname;
      }
      const hostParts = hostname.split(".");
      if (hostParts.length > 2) {
        const lastTwo = hostParts.slice(-2).join(".");
        if (/^(co|com|org|net|edu|gov|mil)\.[a-z]{2}$/i.test(lastTwo)) {
          return hostParts.slice(-3).join(".");
        }
      }
      return hostParts.slice(-2).join(".");
    } catch (_error) {
      return "";
    }
  }
  normalizeFrontmatterValue(value) {
    if (Array.isArray(value)) {
      return value.map((item) => String(item).trim()).filter(Boolean).join(", ");
    }
    return String(value || "").trim();
  }
  splitMarkdownLine(line) {
    const indentMatch = line.match(/^\s*/);
    const indent = indentMatch ? indentMatch[0] : "";
    let remainder = line.substring(indent.length);
    let prefix = "";
    const prefixPatterns = [
      /^\[\^[^\]]+\]:\s*/,
      /^>\s*/,
      /^#{1,6}\s+/,
      /^-\s\[[ xX]\]\s+/,
      /^[-*+]\s+/,
      /^\d{1,3}[.)]\s+/
    ];
    let matched = true;
    while (matched && remainder) {
      matched = false;
      for (const pattern of prefixPatterns) {
        const match = remainder.match(pattern);
        if (match) {
          prefix += match[0];
          remainder = remainder.substring(match[0].length);
          matched = true;
          break;
        }
      }
    }
    return { indent, prefix, content: remainder };
  }
  getLineStart(raw, offset) {
    const lineBreak = raw.lastIndexOf("\n", Math.max(0, offset - 1));
    return lineBreak === -1 ? 0 : lineBreak + 1;
  }
  getLineEnd(raw, offset) {
    const lineBreak = raw.indexOf("\n", offset);
    return lineBreak === -1 ? raw.length : lineBreak;
  }
  needsYamlQuotes(value) {
    const trimmedValue = String(value || "").trim();
    return FRONTMATTER_NEEDS_QUOTES_RE.test(trimmedValue) || /^\d/.test(trimmedValue) || FRONTMATTER_RESERVED_RE.test(trimmedValue);
  }
  normalizeTagForComparison(tag) {
    return String(tag || "").trim().replace(/^['"]|['"]$/g, "").replace(/^#/, "").replace(/\s+/g, "_");
  }
  formatFrontmatterTag(tag) {
    const normalized = this.normalizeTagForComparison(tag);
    if (!normalized) {
      return "";
    }
    return this.needsYamlQuotes(normalized) ? `"${normalized.replace(/"/g, '\\"')}"` : normalized;
  }
  async applyMarkdownModification(file, raw, start, end, mode, payload = "", autoTag = "") {
    if (!raw) {
      raw = await this.app.vault.read(file);
    }
    let expandedStart = start;
    let expandedEnd = end;
    let bodyStart = 0;
    if (raw.startsWith("---")) {
      const secondDash = raw.indexOf("---", 3);
      if (secondDash !== -1) {
        bodyStart = secondDash + 3;
      }
    }
    let expanded = true;
    while (expanded) {
      expanded = false;
      const preceding = raw.substring(0, expandedStart);
      const matchBack = preceding.match(/(<mark[^>]*>|\*\*|==|~~|\*|_|\[\[|\[\^[^\]]+\]:?\s?|\[)$/);
      if (matchBack && expandedStart > bodyStart) {
        const newStart = expandedStart - matchBack[0].length;
        if (newStart >= bodyStart) {
          expandedStart = newStart;
          expanded = true;
        }
      }
      const following = raw.substring(expandedEnd);
      const matchForward = following.match(/^(<\/mark>|\*\*|==|~~|\*|_|\]\]|\]\([^)]+\))/);
      if (matchForward) {
        expandedEnd += matchForward[0].length;
        expanded = true;
      }
    }
    const initiallySelectedText = raw.substring(expandedStart, expandedEnd);
    if (/\r?\n/.test(initiallySelectedText)) {
      expandedStart = this.getLineStart(raw, expandedStart);
      expandedEnd = this.getLineEnd(raw, expandedEnd);
    }
    const selectedText = raw.substring(expandedStart, expandedEnd);
    const newline = raw.includes("\r\n") ? "\r\n" : "\n";
    const lines = selectedText.split(/\r?\n/);
    let fullTag = "";
    const sanitizeTag = (t) => t.trim().replace(/^#/, "").replace(/\s+/g, "_");
    if (mode === "tag" && payload) {
      const prefix = this.settings.defaultTagPrefix ? sanitizeTag(this.settings.defaultTagPrefix) : "";
      const cleanPayload = payload.split(/\s+/).map(sanitizeTag).filter((t) => t).map((t) => `#${t}`).join(" ");
      if (prefix) {
        fullTag = `#${sanitizeTag(prefix)} ${cleanPayload}`;
      } else {
        fullTag = cleanPayload;
      }
    } else if ((mode === "highlight" || mode === "color") && this.settings.defaultTagPrefix) {
      const autoTagSetting = sanitizeTag(this.settings.defaultTagPrefix);
      if (autoTagSetting) {
        fullTag = `#${autoTagSetting}`;
      }
    }
    if (autoTag) {
      const cleanAutoTag = sanitizeTag(autoTag);
      fullTag = fullTag ? `${fullTag} #${cleanAutoTag}` : `#${cleanAutoTag}`;
    }
    const processedLines = lines.map((line) => {
      let cleanLine = line.replace(/<mark[^>]*>/g, "").replace(/<\/mark>/g, "");
      if (mode === "highlight" || mode === "color" || mode === "tag" || mode === "remove") {
        cleanLine = cleanLine.split("==").join("");
      } else if (mode === "bold") {
        cleanLine = cleanLine.split("**").join("");
      } else if (mode === "italic") {
        cleanLine = cleanLine.split("*").join("");
      }
      if (mode === "remove") {
        return cleanLine;
      }
      const { indent, prefix, content } = this.splitMarkdownLine(cleanLine);
      if (!content.trim()) {
        return line;
      }
      const trimmedContent = content.trim();
      const tagStr = fullTag ? `${fullTag} ` : "";
      let wrappedContent = trimmedContent;
      if (mode === "highlight" || mode === "tag") {
        if (this.settings.enableColorHighlighting && this.settings.highlightColor) {
          wrappedContent = `<mark style="background: ${this.settings.highlightColor}; color: black;">${trimmedContent}</mark>`;
        } else {
          wrappedContent = `==${trimmedContent}==`;
        }
      } else if (mode === "color") {
        wrappedContent = `<mark style="background: ${payload}; color: black;">${trimmedContent}</mark>`;
      }
      return `${indent}${prefix}${tagStr}${wrappedContent}`;
    });
    const replaceBlock = processedLines.join(newline);
    const newContent = raw.substring(0, expandedStart) + replaceBlock + raw.substring(expandedEnd);
    await this.app.vault.modify(file, newContent);
    if (mode !== "remove" && this.settings.enableFrontmatterTag && this.settings.frontmatterTag) {
      const targetTag = this.formatFrontmatterTag(this.settings.frontmatterTag);
      if (targetTag) {
        try {
          await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
            if (frontmatter.tags === void 0 || frontmatter.tags === null) {
              frontmatter.tags = [targetTag];
              return;
            }
            if (Array.isArray(frontmatter.tags)) {
              const existingTags = frontmatter.tags.map((tag) => this.normalizeTagForComparison(tag));
              if (!existingTags.includes(this.normalizeTagForComparison(targetTag))) {
                frontmatter.tags.push(targetTag);
              }
            } else if (typeof frontmatter.tags === "string") {
              const existingTags = frontmatter.tags.includes(",") ? frontmatter.tags.split(",").map((t) => t.trim()) : frontmatter.tags.split(/\s+/).map((t) => t.trim());
              const cleanTags = existingTags.filter((tag) => this.normalizeTagForComparison(tag) !== this.normalizeTagForComparison(targetTag) && tag !== "");
              if (cleanTags.length === existingTags.length) {
                frontmatter.tags = [...cleanTags, targetTag];
              }
            }
          });
        } catch (e) {
          console.error("Reader Highlighter Tags: Failed to inject frontmatter tag.", e);
        }
      }
    }
  }
  restoreScroll(view, pos) {
    requestAnimationFrame(() => {
      applyScroll(view, pos);
    });
  }
};
var ReadingHighlighterSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Reader Highlighter Tags Settings" });
    new import_obsidian5.Setting(containerEl).setName("Toolbar Position").setDesc("Choose where the floating toolbar should appear.").addDropdown((dropdown) => dropdown.addOption("text", "Next to text").addOption("top", "Fixed at Top Center").addOption("bottom", "Fixed at Bottom Center").addOption("left", "Fixed Left Side").addOption("right", "Fixed Right Side (Default)").setValue(this.plugin.settings.toolbarPosition).onChange(async (value) => {
      this.plugin.settings.toolbarPosition = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Highlighting" });
    new import_obsidian5.Setting(containerEl).setName("Enable Color Highlighting").setDesc("Use HTML <mark> tags with specific colors instead of == syntax.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableColorHighlighting).onChange(async (value) => {
      this.plugin.settings.enableColorHighlighting = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.enableColorHighlighting) {
      new import_obsidian5.Setting(containerEl).setName("Highlight Color").setDesc("Hex code for the default highlight color.").addColorPicker((color) => color.setValue(this.plugin.settings.highlightColor || "#FFEE58").onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian5.Setting(containerEl).setName("Enable Color Palette").setDesc("Show a palette of 5 colors in the toolbar for quick selection.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableColorPalette).onChange(async (value) => {
      this.plugin.settings.enableColorPalette = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.enableColorPalette) {
      containerEl.createEl("h4", { text: "Color Palette" });
      this.plugin.settings.colorPalette.forEach((item, index) => {
        new import_obsidian5.Setting(containerEl).setName(`Color ${index + 1}: ${item.name}`).addColorPicker((color) => color.setValue(item.color).onChange(async (value) => {
          this.plugin.settings.colorPalette[index].color = value;
          await this.plugin.saveSettings();
        })).addText((text) => text.setPlaceholder("Auto-tag (optional)").setValue(item.tag).onChange(async (value) => {
          this.plugin.settings.colorPalette[index].tag = value;
          await this.plugin.saveSettings();
        }));
      });
    }
    containerEl.createEl("h3", { text: "Tags" });
    new import_obsidian5.Setting(containerEl).setName("Default Tag Prefix").setDesc("Automatically add this tag to every highlight (e.g., 'book').").addText((text) => text.setPlaceholder("book").setValue(this.plugin.settings.defaultTagPrefix).onChange(async (value) => {
      this.plugin.settings.defaultTagPrefix = value.replace(/\s+/g, "_").replace(/^#/, "");
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Smart Tag Suggestions").setDesc("Suggest tags based on recent usage, folder, and frontmatter.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSmartTagSuggestions).onChange(async (value) => {
      this.plugin.settings.enableSmartTagSuggestions = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Enable Smart Paragraph Selection").setDesc("Snap selections inside a paragraph, list item, heading, or blockquote to the entire block.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSmartParagraphSelection).onChange(async (value) => {
      this.plugin.settings.enableSmartParagraphSelection = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Quote Template" });
    new import_obsidian5.Setting(containerEl).setName("Quote Format").setDesc("Template for copying text as quote. Variables: {{text}}, {{file}}, {{path}}, {{date}}, {{time}}, {{domain}}, {{author}}").addTextArea((text) => text.setValue(this.plugin.settings.quoteTemplate).onChange(async (value) => {
      this.plugin.settings.quoteTemplate = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Annotations" });
    new import_obsidian5.Setting(containerEl).setName("Enable Annotations").setDesc("Add comments to selections as footnotes.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAnnotations).onChange(async (value) => {
      this.plugin.settings.enableAnnotations = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show Annotation Button").setDesc("Show the annotation button in the toolbar.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showAnnotationButton).onChange(async (value) => {
      this.plugin.settings.showAnnotationButton = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Reading Progress" });
    new import_obsidian5.Setting(containerEl).setName("Track Reading Progress").setDesc("Remember scroll position when leaving a file.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableReadingProgress).onChange(async (value) => {
      this.plugin.settings.enableReadingProgress = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Clear Reading Positions").setDesc(`Currently tracking ${Object.keys(this.plugin.settings.readingPositions).length} file(s).`).addButton((button) => button.setButtonText("Clear All").onClick(async () => {
      this.plugin.settings.readingPositions = {};
      await this.plugin.saveSettings();
      new import_obsidian5.Notice("Reading positions cleared.");
      this.display();
    }));
    containerEl.createEl("h3", { text: "Toolbar Buttons" });
    new import_obsidian5.Setting(containerEl).setName("Show Tag Button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showTagButton).onChange(async (value) => {
      this.plugin.settings.showTagButton = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show Quote Button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showQuoteButton).onChange(async (value) => {
      this.plugin.settings.showQuoteButton = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show Remove Button").addToggle((toggle) => toggle.setValue(this.plugin.settings.showRemoveButton).onChange(async (value) => {
      this.plugin.settings.showRemoveButton = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Mobile & UX" });
    new import_obsidian5.Setting(containerEl).setName("Haptic Feedback").setDesc("Vibrate slightly on success (Mobile only).").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableHaptics).onChange(async (value) => {
      this.plugin.settings.enableHaptics = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show Button Tooltips").setDesc("Show tooltips when hovering over toolbar buttons.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showTooltips).onChange(async (value) => {
      this.plugin.settings.showTooltips = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Frontmatter Integration" });
    new import_obsidian5.Setting(containerEl).setName("Auto-tag highlight in Frontmatter").setDesc("Automatically inject a specific tag into the note's frontmatter whenever you highlight text.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableFrontmatterTag).onChange(async (value) => {
      this.plugin.settings.enableFrontmatterTag = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.enableFrontmatterTag) {
      new import_obsidian5.Setting(containerEl).setName("Frontmatter highlight tag").setDesc("The tag to add (e.g. 'resaltados'). Do not include the # symbol.").addText((text) => text.setPlaceholder("resaltados").setValue(this.plugin.settings.frontmatterTag).onChange(async (value) => {
        this.plugin.settings.frontmatterTag = value.replace(/^#/, "");
        await this.plugin.saveSettings();
      }));
    }
  }
};
